var canvas = document.getElementById('canvas');
var context = canvas.getContext('2d');
var snake;
var snake_size = 10;
var wid = 200;
var hei = 200;
var score = 0;
var epoch = 0;
var fruit;
var data_json = [];